### ISSUE TITLE
E-Mail sharing not working (?)

### ISSUE THREAD

**Issue by gitvitox** [networkteam/Networkteam.Neos.Shariff#25]
Hey,

It seems that somehow the E-Mail function is not working. If I click on the "Share with Mail" button, I will only get redirected to `http://site.localhost/site.html?view=mail`

These are my Settings:
Settings.yaml
```yaml
Networkteam:
  Neos:
    Shariff:
      options:
        domain: 'http://site.localhost'
        services:
          - WhatsApp
          - Twitter
          - Facebook
          - LinkedIn
          - Xing
          - Mail
```

I am also gettings this error on the console everytime I load the page:
```
Uncaught TypeError: o.getJSON is not a function
    at e.value (shariff.min.js:7)
    at new e (shariff.min.js:7)
    at HTMLDivElement.<anonymous> (shariff.min.js:7)
    at Function.each (jquery.slim.min.js:2)
    at E.fn.init.each (jquery.slim.min.js:2)
    at HTMLDocument.<anonymous> (shariff.min.js:7)
    at e (jquery.slim.min.js:2)
    at t (jquery.slim.min.js:2)
```
